apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  encryptedData:
    admin-password: AgBz7S0aSJ/X4v/k+J8f3p8GPugPC6JsWz1WCq2i5oC6TELIOdWIBK8BFhQEPv/2so0BNEc9EunMxLE5pJre0Vogw0B+mG68nfO6tMn93LABpaSwMZBe6492KXE65nsHUT3tKDRhZBzhN0HZWGLk+rnEa+9/1sgJvZgtLGt8zqmSieCCXGtc9mJ1TXp6HMbyK5DEFq4QhkAqMtO7n8pSjZQGOzK5RprFeXcENOzvWDTS4FULlLH1YXpnS64LAaDenH1+GLxzaiRvwquag+bo6gkQqxEADJcwB6Mu1Vj/BSBXCzC8OXH9cbtui9Xza2PkbA/1tcm01N/0ivdAlT6+Qq/AFxSBGG7o6pPiPuwsu9ios5cv3IWNpZOqJYTNCNDR9RdSTHSbOvUNmRzT35EkSDlGCn/yiTwETz4XgZ8LV+5GHccm0VAh4hI2Qzu1wW47qAwzhUrJPqo7CRRBmOcCjoi57QUQU0S2d6jETB/509Gi6aQZlSXriMWo6pdFJVj0SJjFR8NA8qzogu3/QSYP+WBPwSNyPUFFOFaT1uH0QKKrBseMk8V23+/S5QtTIQITmyx0N+h9JJrnESZPzKnq/hPwphuzZtl+Fpqd2wn+G+oKhIajsAicNC9Q0dxiqsg6WP4Di8kh0dHVADfXTuELK5RkdcrRQqCTZPt4TWHlyzdbq0/HaFD0WXFK4vE/UkSi0gALUUJD7MuA/JFlArYeKkNQIs5aLA==
    admin-user: AgCBedhI73uupPNtZKvkkDY5FD+xntSy4JcT/qzYfSXVdHoG7nfjPCODuy1TIy1ZBt2bGD1mLhte2Ndn1bfeec2Ky2bdvMVmZTU+uczgVswS4xGL/AW0kLtWXxvis5Ty0qXMznWj1e77N95Eofdll6uw+mpf6rFsUg9PV0lnHG8hRndqcaJ8BB7KmTdqB9fbV7K2YbvQELPn8EscOcaiHInyjn7ecKmCz32rS/L1e58dQSR5MeIa/0vL3liEOfgYBxh6bfz9yEH7r03ULZwvMEkxzjw3kqhQ3HFKPHlAUE7MLoTurz7vbkc10dTs1bJ4B3efJzALF9olr7Kzsf8IOisre3CkEX6URBLoIheHTAGvTTge23w8pRDVd2JVHsxM1O5h9Z40BZCTcLPkD6fSEe/i5fxC5DEZ7m9hZzf2omoo1X1JRzv7OMRJARgIdfx0G73MxIZKIbQS3YWX4j+C224LW0hmrrXeOZVfCxGTzE4MazGN8x0sgUlkrf+pbG2ds/XB2gjUOzrzEG9nXqQo1otapngK4CFyqTrAlmNZx2T+1AXKytVUOhTfCRW8HV3rbsbho93NqHApswmXLLRwULB/C/MJrl3zSsmLl7/V2KCwwfvvl/24qCuZAZL/iMbHVB6j/Ef9Mq1GS2C1uYVIwP2dc56jiy/jLFpUqnT5vfFHVtB4KtWiQ+KXGcKgVSmIXkmRlOp5Xw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
