apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  encryptedData:
    admin-user: AgAXajUE9ngQXaIb1HApd5APHZpu0gw2p13SBRMtS2/2ysXqZMJRsjqztEbuNNZoFK1Gtzxgj+kKdT3V5uSEdG2Iupo5HlKL0D4PX0dAN7TDz+09ufn2s6aaTYza/ndFpYSuaHNQqoycKHTRuG1E47gq/M16r5NqgUaWYy9eXOs279/mpHeT/Ug6U37dw8fjfo79FeIalTXhfMfr0/D5cmsnFh0WU3dlEnt7yvNgVXlQsyfrvMS6Yw2YDoojERSJZP9/aeu0q3ZkwBoOkALfCIW6YDVGGeyv+CdmK0jsvjHBILmeau430UfNqhnihL/fIFgH0YcD8HnrMWh13uGVrdJxIq2PURA/JeTVW0h8FAXCNiMByRV0RjWFKfJwVZdxIahlhGdb1GCEpp3RUZkuxUWYzbLEPBaqWclbiLI3fXTYTv09uIGtA1zHCeQ9cGW4s6yrjCVL1E/lP84j0SbZdn+hoXUf0ESfkLZWCywsnr8gTCgOCfw3oIB/+sRi5WW/obaDhRM26mM0PW4oM9OUFXmhBmCJV4oGkRBNmfJnnRJbwX+6yf6owXuI+kGs1i//s+3wM+O4LfgTcLakzqyPR+6E00IYSRK3+DvjSQHJU1+37iuj7Xn8MmyCBod9IAoizpKjpTZPxAydeyGHeXFHRzsau/lTSo0l7MQQlkoSJu3B+y6TUojQHld1Vu6jjA3kV2HzJslpv6tA3DnefMN16jxJ
    admin-password: AgBgHucPsct2W4STwoevSDPwCvpM7A9MnjPvz1HoRICThnwBy8XWnmimtxc6WDUdRrVhSVfF/uahnjbI3sprqCGv4jl6/t1V9uLm+aGNoPlaSIWYuhyB3lDumK3ank3KEPWwhIVGZNxvSNGVXdhpiMFOYM6CVzBqXGrL7201QjFCq00HwNCqTJv+JybzUdTRl2elgb/ztsHD1k0UjdI7rBNHoEG4+nhi27mibjaa9PWbgHBzE4bnE2W95wiVtxRzpsF1gp1FxrxxPwQsHBwx0tXMuGpsTayOSnFjufHvegE2HLxTzUdSaX3EEevUehDu1WO1vmFlgnp0ZdFBe7aI0Qaf94S/9NIYDRQ9aaqCiub93gEULt6YDWFl46RaWeKNSwNlyzfEWujM9uUzzASkN9h/Gj6OeS74huwqSiLEydeK6ZOVp1AjMuvwytojXSCt17EMk4WgcJo2sn/rtvjpYxaOLIlwrfnWPazj6sWS0PV4cYF7kcRlCXNXPLqxIj4tSkL33T6peKcPRojzJ3llM6XDsdaHfbz8+SiRzOVO5uBPNuPFVDjBKZIH2RHzHOEHwkm/z9Wxo7TjN31oLxgCCKKwWzBJk7VVHM7DnZA6Be6vYQxiOSJsGNu3W6TKBh6m/72zwtjfva8NJOgXw3fIfmUIfAKnbeC8LHB0R+SzJy9TvSg5ognSSftMwJGe1iME0ok2bLuZQg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
