apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - loki-datasource.yaml

configMapGenerator:
  - name: grafana-dashboard-loki
    files:
      - loki-logs.json=dashboards/loki-logs.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "Логи"

  - name: grafana-dashboard-postgres
    files:
      - postgres.json=dashboards/postgres.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "Базы данных"

generatorOptions:
  disableNameSuffixHash: true
