apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub
  namespace: hub
spec:
  ingressClassName: traefik
  rules:
    # основное имя — корень зоны
    - host: pivasik.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hub-api
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hub-web
                port: { number: 80 }

    # временный запасной вход, убрать после проверки
    - host: hub2.pivasik.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hub-api
                port: { number: 8000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hub-web
                port: { number: 80 }
