apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-secret
  namespace: app-demo
  annotations:
    # страховка: случайное удаление файла из git не должно унести пароль БД.
    # Argo оставит объект, а не запрунит его вместе с каскадным Secret'ом
    argocd.argoproj.io/sync-options: Prune=false
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBWAvmok0Ceo3DdFtM5moqBlzaxQY0lHaK7qRPKJkLzoifUbdk7V5Li9s4/bPh5cR+bLLfmIm6FZV0ln+ma0SsOHDm38fuSZcQePZexHVC/tvQ+ThiLDOdrRFeDTXl3oX6v6bUCWgGpH3lhWmGLS5Y6+ArxuLPkJ8wX/Bq5CkVBt0oTBc2oL9BMKAJWMRJZOCxRWCIDUVngLXmwM0cTkbJWo0dZKUwpoyYAfGo9a3Ju7aNSn0qfIlPKw0BGK2yJA38uW7K4zwld7NjrtRmXshsArdfNCA7HsAbe0VUSTk98knC56M3d3a7FR1KnEnyDiani40G0PpaWzTkiaeJlkfQoBRKvGnVXJcVbmrS4N32uYDA5wE/i9CBpi9qYWYNpKzroAtR4R57W0wL/P6ORSwO7u7CNJeS/4GnOAOBmv1WGKDS1/GPEHz4UPGvskndu7KXyTrYNH+CsGJQ+4pGbRHcd89dYUpyO9481kRVe7ucJ5q5xfyaHNSX1tKEePh/MBLPhGKpnOKVY8V9svh32YXNwHkjq0GQKNH7rocfrWR4gbYPkyFe6veDhdneTdxoVVE9sq5BpxyUaQkPbpPAc3/WqhtYHLGONlP4UXokZiAbnIFjmypAtswRAQEm4+KT4vuPAU/uKEK38h6Djh5cenLEWUS2vNRaxdEKYzE7vS5ypqyWsgONo0+WAefCq3+3C2U2RLkDnppQhrQ==
  template:
    metadata:
      name: pg-secret
      namespace: app-demo
    type: Opaque
