---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: longhorn-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgB81Tl+9Gk1eLQAZFtHfW+3dAh4sdS3LmiYnkjYlJpUSeHC+BsH1M/vulxg94PsReeHHQhWOYdGefKuEh/81yGAiy8ytrzFaZH+Oges7k96y2oWB64X+LKSlVpJsW976/71ogPgR+R0tdfblej6MHr3YGc6WeEo4cZCDSoIm6xUsmoMmHgoAu+DnVZ36HhyhGEqYDiosHmtTeBRNEzKaAgnW8OBrkFPV7bVph9XqnW5WABZWVGK6G1gDlYHCbmpB1rKLLz6cZaSsvcGH516AjqQQNyaMvVAKMrUu8ub+IocSkqqmQ54RzFTRjg0OENyltzkYfqxPldK8of5YDCHQ8rPccHHQduRcIOUHrCZuVPA53eExAu5Iz0KlS2sVN/zHpanOJFnpkVjGALmB38gYGJEQkSEWXBQ+jgOQubVQmhtbhCL+hWPyijDM5ncZgwRDQw9VYEEcWLCpu7qzpPsU7Mwgu9gh5E2knzlFc0j4UzKeaJKxqfxo/n5/tKma/lBcmW/SD4kbNLRegr3U6BcXNb3r7p5f2cv0zGlN42ZtNa7u82u+3udrWmZhUQkU3HwHtakcXcKwWa3CI3ebU5EBkH2/T7NLTFUPYRDb6jitJycU8OrLOHrTSr2ob104thTq7MybBZFS5/IDqR/hdA3/hBLYbNTvyCXYikxn/hERxwivz6giESi4JYmZqomJY+Q+jvn87aEqFD2HKtX918/ebvUnOx8LDUbfeUg6i8EtvcUVcSWxiV3COt9rSXcvA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: longhorn-auth
      namespace: longhorn-system
    type: Opaque
