{
 "title": "Loki",
 "description": "k3s loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   },
   { "name": "Search", "query": ".+" }
  ]
 },
 "panels": [
  {
   "title": "Time series (Ошибки)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (pod) (count_over_time({namespace=~\"$namespace\"} |~ \"(?i)error|fatal|panic|exception\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Time series (Объем контейнеров)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container) (count_over_time({namespace=~\"$namespace\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"} |~ \"$Search\""
    }
   ]
  },
  {
   "title": "Stat",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$namespace\"} |~ \"(?i)error|fatal\" [$__range]))"
    }
   ]
  }
 ]
}