---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: registry
spec:
  encryptedData:
    users: AgAXqAQ/u5r9ScBeDh1S10fNuj5+23UB+gBI8loWM8iGd4DX2S1nc99irw8UozbWXJqRh7IXCl3+yb53+l2QPTjfSwYuC7NBzzXsYX4r+B4omVqO97URRbkU4hC1aH4girhjgyODU5oNandHLgvxTOw5KFJtUgasr4aOlEeCS2pYALCr+1ZvMfPeaFOYxMT2Bbj25/Ccon4NwjETT6AOxoEUy8j7Te+dfr8DqAsxRjZXz9FmMyaNrwZiFyo0xxffnjC8/0Pd4Holu1UWcyhTKRFVjc0k3PvHKdA6/B3xGrY+0I11TOpfvavJJIH0kGHdWNIBMldyPB71QO6GdciKAhn9IUJrj2uQxLyPOQs25TrTGphFP37fmFAQ2IJpvQ4/l248JGSpyiYlxyQbyAAI31gJvfLlXd2IZAugZXUQQKPHvO182rAH1nrIOpeDz8+UNuhSlXUNwsSZlTV6eGHo1L98iY0P3TilE/L3B2T25HncAF1LrDf9Mj2WWRjC8fXk86HZTXJzj0vkmdbYw9vpPwfWSTqBmsQMG5yMU7AoApDz4DcB5xtkFR3kovDY1j+1y+22t1c0qffexb9OO7jMplLOP2Ot1Xto7W2Lsv+6fqXwAz76YKgTtT28F27EeseudALXsFvfqhH0WLgXfbz3j5HaSUvusM8U69AYIiEcZYvkCJbL0a5VleGwqhkKx+qLHVKXt4S/fDgSFPOx4wV1NHZjkaAL1kCZI+r2Gsd6AgzX6u/A4BDnR058i8nCtjvhqz4kXKBThL1QrTzq+zPXW1fyBw==
  template:
    metadata:
      name: registry-auth
      namespace: registry
