apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kofie4ik/k8s-stand.git
    targetRevision: HEAD
    path: manifests/hub
  destination:
    server: https://kubernetes.default.svc
    namespace: hub
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
