apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki             # ← имя релиза Helm, менять нельзя
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.55.0
      helm:
        valueFiles:
          - $values/helm-values/values-loki.yaml

    - repoURL: https://github.com/Kofie4ik/k8s-stand.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # automated включим после проверки
  syncPolicy: {}
