apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.0
      helm:
        valueFiles:
          - $values/helm-values/values-longhorn.yaml

    - repoURL: https://github.com/Kofie4ik/k8s-stand.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
