persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Delete

csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 2
  snapshotterReplicaCount: 2

defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: false
  backupTarget: nfs://10.0.2.1/srv/longhorn-backup

longhornUI:
  replicas: 1

ingress:
  enabled: false

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring

preUpgradeChecker:
  jobEnabled: false
